import time

name = "디즈니랜드"
stage = 4 # 작동하는 스테이지
req_like=(200000,'<') # (요구 호감도 , '=' : 같을때 '<' : 같거나 높을때 '>' : 같거나 낮을때)
is_couple=False # 커플일때만 발동되는 씬인지

def script(game):
    game.img("blank.png")
    game.fade_out()
    game.background("room_morning.jpg")
    game.n("그로부터 몇 주 뒤...")
    game.n("휴대폰의 알람이 득달같이 울린다.")
    game.n("반쯤은 떠지지않은 눈을 비비며 발신자를 확인했다")
    game.n("써니..?")
    game.me("이런 이른 시간에 무슨 일이야?")
    game.p("야! 시간이 몇신데 아직도 자고 있어?")
    game.me("아.. 미안..")
    game.p("너 오늘 뭐해?")
    game.me("오늘? 학교가야지?")
    game.p("아니, 오늘 학교쉬는날인데 무슨 소리람!")
    game.p("빨리 준비해! 오늘 우리 데이트야!")
    game.me("예에!?!?")
    game.fade_in()
    game.n("눈이 번쩍 떠졌다")
    game.p("디즈니랜드 갈거야! 준비빨리해!")
    game.n("전화가 뚝 끊겼지만 움직일 수 없었다.")
    game.n("데이트란 단어가 머리속에서 떠나지 않았다.")
    game.n("데이트... 데이트...")
    game.n("얼른 준비하고 집을 나섰다.")
    game.background("train.jpg")
    game.p("야!!!파이!!!")
    game.n("기차안에서 써니가 나를 발견하고는 환하게 웃으며 손을 흔든다.")
    game.img("date/hi.png")
    game.n("기차안의 공기는 설렘의 색으로 칠해졌다.")
    game.me("써니.. 너 데이트간다고 힘 많이줬네..?")
    game.p("당연하지! 오늘 하루종일 너랑 같이 있을 생각하니까 너무 신나!")
    game.n("기차안의 풍경이 빠르게 지나가는만큼")
    game.n("내 심장도 빠르게 뛰기 시작했다.")
    game.me("나도 오늘 하루종일 너랑 같이 있을 생각하니까 너무 좋아")
    game.n("간질거리는 설렘이 온몸을 감싸안았다.")
    game.p("그나저나 파이썬공부는 얼마나했어?")
    game.sel("이말을 데이트때 해?","그보다 너오늘 너무 눈부셔 아..햇빛인가?","공부는 조금후에 해도괜찮아")
    if game.choice == 1:
        game.like -= 10
        game.p("이말을 데이트때 해??")
        game.img("date/angry.png")
        game.p("넌 파이썬공부안해..?")
    elif game.choice == 2:
        game.like += 10
        game.p("아 뭐래~!")
        game.img("date/blush.png")
    elif game.choice == 3:
        game.like += 15
        game.p("맞아! 공부는 나중에 해도되지!")
        game.img("date/happy.png")
    game.n("기차는 계속해서 달려갔고, 결국 디즈니랜드에 도착했다.")
    game.background("disneyland.jpg")
    game.img("date/idle.png")
    game.n("디즈니랜드의 입구는 생각보다 훨씬 더 화려했다.")
    game.n("온갖 캐릭터들이 나를 반겨주는것 같았다.")
    game.n("하지만 캐릭터들보다 더 내눈을 사로잡은건 써니였다.")
    game.p("파이 그만좀 멍때려! 그보다 얼른 들어가자!")
    game.img("date/hands.png")
    game.n("우리는 손을 잡고 디즈니랜드 안으로 들어갔다.")
    game.me("와.. 진짜 대박이다!")
    game.p("그치? 빨리 가자!")
    game.img("blank.png")
    game.background("themepark.jpg")
    game.n("우리는 롤러코스터를 타기 위해 줄을 섰다.")
    game.n("써니는 신나서 계속 떠들어댄다.")
    game.p("파이! 빨리 와!")
    game.me("응. 금방갈게!!")
    game.background("roller_coaster.jpg")
    game.n("사..살려줘...")
    game.fade_out()
    time.sleep(1)
    game.background("themepark.jpg")
    game.fade_in()
    game.n("............")
    game.n("롤러코스터는 생각보다 훨씬 더 무서웠다.")
    game.n("기뻐보이는 써니와는 다르게 내심장은 쿵쾅거렸다.")
    game.me("나는 조금 무서웠어.. 괜찮아?")
    game.p("응? 나 너무 신나!!")
    game.img("date/happy.png")
    game.n("방방뛰며 얘기하는 써니가 날 미소짓게했다.")
    game.img("date/blush2.png")
    game.p("파이 너도 신났지?")
    game.n("아까말했던 내용도 까먹을 정도로 재밌었구나...")
    game.n("문득, 조금 전 무섭다고 하던 내가 조금은 부끄러웠다")
    game.p("저기도 가보자 저기저기!!")
    game.img("date/hands.png")
    game.n("이제 제법 익숙해진걸까?")
    game.n("우리는 손을 잡고 새로운 장소로 향했다.")

    game.background("water.jpg")
    game.img("date/blush3.png")
    game.n("어쩐지 신나는 느낌을 참을수없다는듯이 써니가 놀이기구를 쳐다봤다")
    game.p("파이! 저기 후룸라이드!")
    game.me("오! 재밌겠다!")
    game.p("빨리 가보자!!!")
    game.me("응! 가자!")
    game.n("우리는 후룸라이드를 타기 위해 줄을 섰다.")
    game.n("점점 더워지는 날씨에 물놀이기구는 최고의 선택이었다.")
    game.n("수많은 인파속에서 우리의 시간은 눈부시게 빛났다.")
    game.img("blank.png")
    game.n("놀이기구가 시원한 물줄기를 뿜어내며 우리를 반겼다.")
    game.n("서서히 출발하는 배는 물살을 거칠게 가르며 나아갔다.")
    game.n("우리는 물속으로 빠져들어갔고, 시원한 물줄기가 우리를 감싸안았다.")
    game.img("date/shower.png")
    game.p("아니 이게 뭐야!! 다 젖었잖아!!!!으..")
    game.me("하하하.. 괜찮아! 나도 다 젖었어!")
    game.p("해가 쨍쨍하니까 금방 마르겠지..")
    game.img("blank.png")
    game.background("themepark.jpg")
    game.n("평화로운 시간들이 지나간다")
    game.me("늘 노는 시간은 너무 빨리가는것 같아")
    game.p("맞아!!")
    game.n("묘하게 굳어있는 써니의 표정이 신경쓰였다.")
    game.img("blank.png")
    game.fade_out()
    time.sleep(1)
    game.n("어느새 어둠에 물든 놀이공원의 전경이 눈에들어왔다")
    game.background("disneyland_night.jpg")
    game.fade_in()
    game.n("....")
    game.img("date/angry.png")
    game.p("아직 타보고싶은게 산더미인데 벌써!!!")
    game.n("써니는 분에 겨운듯 씩씩댔다.")
    game.p("아! 나 타고싶은거 있으니까 가자!")
    game.n("나는 얌전히 고개를 끄덕이며 이끄는 방향으로 향했다.")
    game.img("blank.png")
    game.background("ferris_wheel.jpg")
    game.n("......")
    game.n("잠시간의 침묵이 흘렀다.")
    if game.like>=90:
        game.img("date/blush.png")
        game.n("주변의 사람들이 눈에 들어오지않았다.")
        game.n("온세상이 우리를 중심으로 흘러가는것 같은 기분")
        game.n("밝게빛나는 조명아래 우리가 함께였다.")
        game.p("파이 너랑있는 시간이 즐거워")
        game.me("나도.. 시간이 가는줄도 몰랐어")
        game.p("그럼..탈까?")
        game.img("blank.png")
        game.n("조용히 끄덕이며 관람차에 올랐다")
        game.p("생각해보면 우린 참 공통점이많은 것 같아.")
        game.me("파이썬 좋아하는거?이름대로 따라간걸까?")
        game.p("그럴지도..")
        game.n("높게 올라간 관라차안엔 얼굴이 상기된")
        game.n("두남녀의 두근거림만 공간에 가득했다.")
        game.n("서로의 두근거림을 가리려 애쓰는 모습이 귀여운 두남녀였다.")
        game.img("date/hands.png")
        game.n("아까도 잡았던손이였는데..")
        game.n("온몸에 있는 세포가 꿈틀대는 기분이였다...")
        game.n("지금 이 순간, 시간이 멈췄으면 한다...")
        game.n("그때, 안내방송이 들려왔다.")
        game.other("저희 놀이공원을 이용해 주셔서 감사합니다.","안내방송")
        game.other("잠시 후 퇴장시간이니 늦지 않게 퇴장해주시길 바랍니다","안내방송")
        game.n("야속하기도 하지...")
        game.me("벌써 시간이 이렇게 됐네")
        game.me("어..얼른 나가자")
        game.img("date/idle.png")
        game.p("그.. 그래! 오늘 재밌었다")
        game.me("나는 잡은 손을 꽉 붙잡았다")
        game.fade_out()
        time.sleep(1)
    elif game.like>=60:
        game.img("date/blush2.png")
        game.n("써니의 모습이 주변 조명아래 밝게 빛났다.")
        game.p("파이! 빨리 관람차타자!")
        game.me("응..!")
        game.img("blank.png")
        game.p("파이 넌 참 괜찮은 애같아.")
        game.n("관람차에서 내려온뒤 묘하게 기분이 좋았다.")
        game.me("나도 파이가 좋은거 같아")
        game.img("date/blush3.png")
        game.p("흐응~")
        game.p("그게 무슨 의미이실까?")
        game.me("그런거 아니거든!")
        game.p("파이야 지금 얼굴 시뻘게")
        game.n("얼굴이 달아오른것이 뒤늦게 느껴진다")
        game.n("그때 안내방송이 들려왔다")
        game.other("저희 놀이공원을 이용해 주셔서 감사합니다.","안내방송")
        game.other("잠시 후 퇴장시간이니 늦지 않게 퇴장해주시길 바랍니다.","안내방송")
        game.me("벌써 시간이 이렇게 됐네")
        game.me("얼른 나가자")
        game.img("date/idle.png")
        game.p("그래! 오늘 재밌었다")
        game.fade_out()
        game.n("나는 써니랑 천천히 웃고 떠들며 집으로 귀가하였다")
        time.sleep(1)
    elif game.like>=30:
        game.img("date/idle.png")
        game.n("재잘거리는 써니의 모습에 기분이 좋았지만.")
        game.n("써니의 눈동자 초점이 흔들리는 모습이 신경쓰였다")
        game.n("무슨일이라도 있는걸까?")
        game.fade_out()
        game.n("우리는 무거운 분위기 속 천천히 어색한 침묵을 이어가며 발걸음을 옮겼다")
        game.background("train.jpg")
        game.img("date/think.png")
        game.n("집으로 돌아가는 발걸음이 왠지 무겁게 느껴졌다.")
        game.fade_in()
        game.img("date/idle.png")
        game.p("오늘 뭔가 연인처럼 굴어서 미안!")
        game.n("정곡을 찔렸다")
        game.p("역시 우린 이런건 좀 안맞는거 같아서... 헤헤..")
        game.me("써니가 편한대로 해도 좋아")
        game.p("그래 오늘 헷갈리게 해서 미안해!")
        game.n("뭔가 씁쓸한 기분이 들었다..")
        game.fade_out()
    else:
        game.img("date/think.png")
        game.n("순식간에 차가워진 공기가 주변을 맴돌았다.")
        game.n("관람차를 타면서 누구보다 신나했을 파이의 표정이 무표정하게 밖을응시했다.")
        game.n("써니의 차갑게 식은표정은 처음보는것같았다")
        game.n("관람차에서 내려올떄까지 말이없던 써니가 조심스레 입을 열었다.")
        game.me("써니야 왜 그래..?")
        game.p("파이, 나 먼저 가볼게...")
        game.fade_out()
        game.img("blank.png")
        game.fade_in()
        game.n("설마,갈까했는데 저멀리 뛰어가듯 사라졌다..")
        game.fade_out()
        time.sleep(1)
    game.stage += 1
    game.end() # 마지막까지 열심히 달렸다..