import time

name = "디즈니랜드"
stage = 4 # 작동하는 스테이지
req_like=(200000,'<') # (요구 호감도 , '=' : 같을때 '<' : 같거나 높을때 '>' : 같거나 낮을때)
is_couple=False # 커플일때만 발동되는 씬인지

def script(game):
    game.img("blank.png")
    game.fade_out()
    game.background("room_morning.jpg")
    game.n("그로부터 몇 주 뒤...")
    game.n("휴대폰의 알람이 득달같이 울린다.")
    game.n("반쯤은 떠지지않은 눈을 비비며 발신자를 확인했다")
    game.n("써니..?")
    game.me("이런 이른 시간에 무슨 일이야?")
    game.p("야! 시간이 몇신데 아직도 자고 있어?")
    game.me("아.. 미안..")
    game.p("너 오늘 뭐해?")
    game.me("오늘? 학교가야지?")
    game.p("아니, 오늘 학교쉬는날인데 무슨 소리람!")
    game.p("빨리 준비해! 오늘 우리 데이트야!")
    game.me("예에!?!?")
    game.fade_in()
    game.n("눈이 번쩍 떠졌다")
    game.p("디즈니랜드 갈거야! 준비빨리해!")
    game.n("전화가 뚝 끊겼지만 움직일 수 없었다.")
    game.n("데이트란 단어가 머리속에서 떠나지 않았다.")
    game.n("데이트... 데이트...")
    game.n("얼른 준비하고 집을 나섰다.")
    game.background("train.jpg")
    game.p("야!!!파이!!!")
    game.n("기차안에서 써니가 나를 발견하고는 환하게 웃으며 손을 흔든다.")
    game.img("date/hi.png")
    game.n("기차안의 공기는 설렘의 색으로 칠해졌다.")
    game.me("써니.. 너 데이트간다고 힘 많이줬네..?")
    game.p("당연하지! 오늘 하루종일 너랑 같이 있을 생각하니까 너무 신나!")
    game.n("기차안의 풍경이 빠르게 지나가는만큼")
    game.n("내 심장도 빠르게 뛰기 시작했다.")
    game.me("나도 오늘 하루종일 너랑 같이 있을 생각하니까 너무 좋아")
    game.n("간질거리는 설렘이 온몸을 감싸안았다.")
    game.p("그나저나 파이썬공부는 얼마나했어?")
    game.sel("이말을 데이트때 해?","그보다 너오늘 너무 눈부셔 아..햇빛인가?","공부는 조금후에 해도괜찮아")
    if game.choice == 1:
        game.like -= 10
        game.p("이말을 데이트때 해??")
        game.img("date/angry.png")
        game.p("넌 파이썬공부안해..?")
    elif game.choice == 2:
        game.like += 10
        game.p("아 뭐래~!")
        game.img("date/blush.png")
    elif game.choice == 3:
        game.like += 15
        game.p("맞아! 공부는 나중에 해도되지!")
        game.img("date/happy.png")
    game.n("기차는 계속해서 달려갔고, 결국 디즈니랜드에 도착했다.")

    game.background("disneyland.jpg")
    game.img("date/idle.png")
    game.n("디즈니랜드의 입구는 생각보다 훨씬 더 화려했다.")
    game.n("온갖 캐릭터들이 나를 반겨주는것 같았다.")
    game.n("하지만 캐릭터들보다 더 내눈을 사로잡은건 써니였다.")
    game.p("파이 그만좀 멍때려! 그보다 얼른 들어가자!")
    game.img("date/hands.png")
    game.n("우리는 손을 잡고 디즈니랜드 안으로 들어갔다.")
    game.me("와.. 진짜 대박이다!")
    game.p("그치? 빨리 가자!")
    game.background("roller_coaster.jpg")
    game.img("date/roller_coaster.png")
    game.n("우리는 롤러코스터를 타기 위해 줄을 섰다.")
    game.n("써니는 신나서 계속 떠들어댄다.")
    game.p("파이! 빨리 와!")
    game.me("응. 금방갈게!!")
    game.img("blank.png")
    game.fade_out()
    time.sleep(1)
    game.background("themepark.jpg")
    game.fade_in()
    game.n("............")
    game.n("롤러코스터는 생각보다 훨씬 더 무서웠다.")
    game.n("기뻐보이는 써니와는 다르게 내심장은 쿵쾅거렸다.")
    game.me("나는 조금 무서웠어.. 괜찮아?")
    game.p("응? 나 너무 신나!!")
    game.img("date/happy.png")
    game.n("방방뛰며 얘기하는 써니가 날 미소짓게했다.")
    game.img("date/smile.png")
    game.p("파이 너도 신났지?")
    game.n("아까말했던 내용도 까먹을 정도로 재밌었구나...")
    game.n("문득, 조금 전 무섭다고 했던 내가 조금은 부끄러웠다")
    game.p("저기도 가보자 저기저기!!")
    game.img("date/hands.png")
    game.n("이제 제법 익숙해진걸까?")
    game.n("우리는 손을 잡고 새로운 장소로 향했다.")

    game.background("water.jpg")
    game.img("date/blush3.png")
    game.n("어쩐지 신나는 느낌을 참을수없다는듯이 써니가 놀이기구를 쳐다봤다")
    game.p("파이! 저기 물놀이기구다!")
    game.me("오! 재밌겠다!")
    game.p("빨리 가보자!!!")
    game.me("응! 가자!")
    game.n("우리는 물놀이기구를 타기 위해 줄을 섰다.")
    game.n("점점 더워지는 날씨에 물놀이기구는 최고의 선택이었다.")
    