import time
# 씬 정보
name = "오프닝"
stage = 0 # 작동하는 스테이지
req_like=(-100,'<') # (요구 호감도 , '<' : 이상 '>' 미만)
is_couple=False # 커플일때만 발동되는 씬인지

def script(game):
    game.img("blank.png") # 화면에 보일 캐릭터 이미지 변경 (아무것도 없는 이미지파일 : blank.png)
    game.fade_out()
    game.n("내 이름은 김파이")
    game.n("나는 요즘 혼자 코딩을 공부한다")
    game.n("그냥 멋있어보여서 시작했는데 취미로는 괜찮다")
    game.n("코딩이란것을 처음해봐서 그런지 너무 어렵지만 열심히 해보기로 했다")
    game.n("20XX년 8월 20일 오즈고등학교 3-2반")
    game.background("classroom.jpg")
    game.img("other/teacher.png")
    game.fade_in()
    game.other("여러분들 과제가 좀 부족하시죠?", "담임선생님")
    game.n("교과목 수학의 담임선생님이다. 자꾸 어려운 수학과제를 수행평가로 내주신다...")
    game.other("네니요....", "반아이들")
    game.other("추가 과제 드리겠습니다!","담임선생님")
    game.other("다음주까지 제출해주세요","담임선생님")
    game.n("반이 순식간에 탄식으로 가득 찼다")
    game.other("그럼 여러분들 오늘도 고생하셨습니다","담임선생님")
    game.other("주말 잘 보내세요!","담임선생님")
    game.n("어제 과제도 다 안끝났는데 큰일났네...")
    game.n("집 가서 어떻게든 다 끝내야지...")
    game.fade_out()
    game.background("school.jpg")
    game.img("blank.png")
    time.sleep(1)
    game.fade_in()
    game.n("학교에서 보내는 시간은 늘 따분하다")
    game.n("새로 시작한 코딩 공부가 학교 공부보단 재밌을지도...")
    game.n("집가면 컴퓨터부터 켜야겠다")
    game.fade_out()
    game.background("day.jpg")
    game.fade_in()
    game.n("화창한 날씨라 걷기 좋은 것 같다") # n = 나레이션 / 혼잣말
    game.img("thony/greet.png") # 화면에 보일 캐릭터 이미지 변경
    game.p("저기, 안녕!") # print()
    game.n("어디서 본거같은데...")
    game.n("같은 수업을 듣는 학생이었나..?")
    game.me("어.. 안녕?") # 플레이어가 하게 될 대사
    game.img("thony/idle1.png")
    game.p("너 혹시 파이썬 재밌어하니..?")
    game.sel("누구더라...","파이썬 정말 재밌지","아니 그닥...","파이썬 너무 좋아 사랑해") # 선택지
    if game.choice == 1: #받아온 선택지
        game.like -= 1 # 호감도 감도
    elif game.choice == 2:
        game.like += 5 # 호감도 증가
        game.p("파이썬 좋아하는구나!")
        game.p("역시 그럴 줄 알았어")
    elif game.choice == 3:
        game.like -= 3
        game.img("thony/angry.png")
        game.p("!!!!!!!!!!!")
        game.me("왜.. 왜그래...")
        game.img("thony/blush.png")
        game.p("미안.. 나도모르게...")
    elif game.choice == 4:
        game.img("thony/blush.png")
        game.p("!!!!!!!!!!")
        game.me("왜.. 왜그래..")
        game.p("그... 앗 아니야")
        game.p("나도 파이썬 좋아해서... 헤헤")
    game.img("thony/idle1.png")
    game.p("어.. 그게.. 나는 옆반의 써니라고해")
    game.p("가방에 파이썬 교재가 있는걸 봤어 우연히 봤어!")
    game.me("그래서...?")
    game.p("내가 파이썬을 진짜 좋아하거든")
    game.sel("입은 옷을 보니 그래보인다...","그렇구나")
    if game.choice == 1: # 선택지 직후에 바로 choice를 부르지 않아도 2번 선택지를 골랐던것을 불러올 수 있습니다!
        game.p("..? 그게 무슨말이야")
        game.me("어.. 아니야")
        game.n("이녀석 바보인가...")
    game.p("아무튼, 친구하고 싶어서 말 걸었어!")
    game.p("우리 친구하자")
    game.sel("그래!","음...")
    game.p("좋다고? 오늘부터 친구인거다 알았지?")
    game.p("이만 가볼게!")
    game.fade_out()
    game.n("써니는 황급히 앞질러 달려갔다")
    if game.choice == 2: # 선택지 직후에 바로 choice를 부르지 않아도 2번 선택지를 골랐던것을 불러올 수 있습니다!
        game.me("난 아직 친구하겠다고 안했는데...")
    game.img("blank.png")
    game.fade_in()
    game.me("좀 특이한 친구네...")
    game.me("머리가 이상한가...")
    game.fade_out()
    game.n("집에 도착했다")
    game.me("과제 바로 해볼까..?")
    game.me("과제 한번 더럽게 어렵네...")
    game.me("5시간 뒤...")
    game.background("room1.jpg")
    game.fade_in()
    game.me("흐아아암...")
    game.me("슬슬 잘 시간인가")
    game.me("벌써 12시네...")
    game.me("과제 다 못 끝냈는데...")
    game.me("붕어빵... 붕어빵...")
    game.me("됐다 잠이나 자자... 주말에 해야지 뭐...")
    game.n("침대에 냅다 눕는다.")
    game.fade_out()
    game.n("다음 날...")
    game.background("room1_day.png")
    time.sleep(1)
    game.fade_in()
    game.me("왜 이리 피곤하지...")
    game.me("어제 너무 늦게잤나...")
    game.n("띠링")
    game.n("핸드폰 알림이 울렸다")
    game.n("썬..? 이게 누구지...")
    game.n("썬 : 파이야 안녕!")
    game.n("썬 : 우리 친구하기로 한거 맞지?")
    game.n("썬 : 번호는 수소문 해서 알아냈어!")
    game.n("갑자기 이상한 친구가 생겼네...")
    game.n("대충 답해둘까....")
    game.n("파이 : 그렇구나 잘 부탁해")
    game.n("썬 : 오늘 시간 돼?")
    game.me("너무 갑작스럽잖아...")
    game.me("")
    game.stage += 1
    game.end()